import type { Metadata } from "next";
import React from "react";
import "./globals.css";
import AuthProvider from "./providers/AuthProvider";
import Header from "./components/common/Header/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <AuthProvider>
        <body>
          <div className="wrapper">
            <div className="container">
              <Header />
              <div className="content">
                {children}
              </div>
            </div>
          </div>
        </body>
      </AuthProvider>
    </html>
  );
}
